DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

-- EMPLOYEE first
CREATE TABLE EMPLOYEE (
    EMPLOYEE_NUMBER BIGINT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    TITLE VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    EMAIL VARCHAR(255),
    HIRE_DATE DATE,
    MANAGER_EMPLOYEE_NUMBER BIGINT,
    DEPARTMENT_DEPARTMENT_NUMBER BIGINT,
    PRIMARY KEY (EMPLOYEE_NUMBER)
);

-- DEPARTMENT second
CREATE TABLE DEPARTMENT (
    DEPARTMENT_NUMBER BIGINT AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(255),
    DEPARTMENT_MANAGER_EMPLOYEE_NUMBER BIGINT,
    PRIMARY KEY (DEPARTMENT_NUMBER)
);

-- Add foreign keys after both tables exist
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_MANAGER
FOREIGN KEY (MANAGER_EMPLOYEE_NUMBER)
REFERENCES EMPLOYEE(EMPLOYEE_NUMBER);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
FOREIGN KEY (DEPARTMENT_DEPARTMENT_NUMBER)
REFERENCES DEPARTMENT(DEPARTMENT_NUMBER);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_MANAGER
FOREIGN KEY (DEPARTMENT_MANAGER_EMPLOYEE_NUMBER)
REFERENCES EMPLOYEE(EMPLOYEE_NUMBER);

DROP SEQUENCE IF EXISTS hibernate_sequence;
CREATE SEQUENCE hibernate_sequence;