DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_NUMBER BIGINT AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(255),
    PRIMARY KEY (DEPARTMENT_NUMBER)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_NUMBER BIGINT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    TITLE VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    EMAIL VARCHAR(255),
    HIRE_DATE DATE,
    MANAGER_EMPLOYEE_NUMBER BIGINT,
    DEPARTMENT_DEPARTMENT_NUMBER BIGINT,
    PRIMARY KEY (EMPLOYEE_NUMBER),
    FOREIGN KEY (MANAGER_EMPLOYEE_NUMBER)
        REFERENCES EMPLOYEE(EMPLOYEE_NUMBER),
    FOREIGN KEY (DEPARTMENT_DEPARTMENT_NUMBER)
        REFERENCES DEPARTMENT(DEPARTMENT_NUMBER)
);

DROP SEQUENCE IF EXISTS hibernate_sequence;
CREATE SEQUENCE hibernate_sequence;